# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilde', models.ImageField(upload_to='bilder/')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleFileUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=b'')),
                ('timestamp', models.TimeField(auto_now=True)),
            ],
        ),
    ]
