# Generated by Django 2.0.4 on 2018-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilde', models.ImageField(upload_to='bilder/')),
            ],
        ),
    ]
