# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 22:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findbestroute', '0003_auto_20180430_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bilde',
            field=models.ImageField(upload_to='bilder/'),
        ),
        migrations.AlterField(
            model_name='multiupload',
            name='files',
            field=models.FileField(upload_to='data_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ocd', 'ocad'])]),
        ),
    ]
