# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findbestroute', '0004_auto_20180501_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiupload',
            old_name='owner',
            new_name='uploader',
        ),
    ]
